services:
  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "5173:5173"
    environment:
      - REACT_APP_GRAPHQL_URI= http://localhost:4000/graphql
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/mydatabase?schema=public
      - NODE_ENV=production
      - PORT=4000
      - GRAPHQL_PLAYGROUND=true 
      - JWT_SECRET=developmentdevelopmentdevelopment
      - PRISMA_HIDE_PROMPTS= true

    depends_on:
      postgres:
        condition: service_healthy
    command: ["sh", "-c", "npx prisma migrate deploy && yarn start"]

  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
